const express = require('express');
const router = express.Router();
const { getProducts, getProductById, createProduct, updateProduct, deleteProduct, updateStock } = require('../controllers/productController');
const auth = require('../middleware/auth');
router.get('/', auth, getProducts);
router.get('/:id', auth, getProductById);
router.post('/', auth, createProduct);
router.put('/:id', auth, updateProduct);
router.delete('/:id', auth, deleteProduct);
router.patch('/:id/stock', auth, updateStock);
module.exports = router;